### PR TITLE
Make trackerfile compliant with 0.88 changes

### LINKED ISSUE #100: Updates in Home Assistant 0.87 & 0.88
Hey buddy, something you may want to work into your wiki as changes to 0.88 have constants moved so therefore locations are broken.

Fix for this in config/custom_components make a new dir called "life360" and move the file "life360.py" from config/custom_components/device_tracker/ to newly created folder config/custom_components/life360/ then rename file from "life360.py" to "device_tracker.py"

Done, not an issue but I believe efficiency is key

Dave.

### PR DESCRIPTION
**Pull request by ludeeus**
Resolves #100.

### CODE REVIEW

**Comment by pnbruckner** [comment]
So what do people do if they're still on a HA version before 0.88?

**Comment by ludeeus** [comment]
It's going to break for them.
Someone will not be happy, it will not be possible (i think) to please everyone 🤷‍♂️

**Comment by pnbruckner** [comment]
@ludeeus, I think what I'll try is to accept your changes to custom_components.json, but also add a new json file (e.g., custom_components_old.json) that maintains the old structure. Then people can point to whichever is appropriate for the version of HA that they're using. (And, of course, I'll update my docs accordingly.) How does that sound?

**Comment by pnbruckner** [comment]
Resolves #100.

**Comment by ludeeus** [comment]
That will work 👌

**Pull request merged**
