### PR TITLE
add pip install life360 to docs

### PR DESCRIPTION
**Pull request by ardation**
It wasn't clear that this needed to be done first.

### CODE REVIEW

**Comment by pnbruckner** [comment]
You shouldn't need to manually install life360 via pip. HA is supposed to do that automatically. It did when I tested it.

**Comment by ianmaddocks** [comment]
I don't know if its related but get the following error after manually installed by placing life360.py file in required folder 

 [homeassistant.loader] Error loading custom_components.device_tracker.life360. Make sure all dependencies are installe...

**Comment by ardation** [comment]
@pnbruckner Yeah I manually ran that command and everything worked correctly. If it helps I am running hassio on a rpi 3b+.

**Comment by pnbruckner** [comment]
@ardation, @ianmaddocks, @ludeeus

I finally got a chance to try starting HA with my life360 custom platform installed manually, and with all its requirements (now life360, timezonefinderL, and indirectly numpy) _not_ installed. In fact, this is the procedure I followed (after first making a backup):

- stop HA
- sudo -u homeassistant -H -s
- source /srv/homeassistant/bin/activate
- pip3 uninstall timezonefinderL
- pip3 uninstall numpy
- pip3 uninstall life360
- deactivate
- cd ~/.cache
- rm -rf pip
- exit

This removed those packages from HA's venv, and even deleted pip's cache. Then I restarted HA. Everything worked fine, including HA automatically installing the required packages.

So it does not appear to me any special effort is involved to get this custom component working, besides what I have documented.

**Comment by pnbruckner** [comment]
@ianmaddocks 
>I don't know if its related but get the following error after manually installed by placing life360.py file in required folder
>[homeassistant.loader] Error loading custom_components.device_tracker.life360. Make sure all dependencies are installe...

Do you remember what version of custom_component/device_tracker/life360.py you had installed when you got this error?

**Pull request closed without merging**
