### PR TITLE
Update main key to make custom_updater work again

### PR DESCRIPTION
**Pull request by pippyn**
Fix for custom_updater. The "name" (main key) of the platform should be in the domain.name format.
https://github.com/custom-components/custom_updater/wiki/components#json-file-examples

### CODE REVIEW

**Comment by pnbruckner** [comment]
@pippyn, with the new layout (starting with HA 0.86), the domain and platform have effectively been reversed. So what was `device_tracker.composite` before is now `composite.device_tracker`. This is why I now have two json files -- one if you're using a version of HA before 0.86, and one for 0.86 and later.

@ludeeus, do I have this right? If so, maybe you could update the description in the json file examples that pippyn references above.

**Comment by ludeeus** [comment]
The example that @pippyn are quoting was something I added after 0.88 to help with the confusion (or so i thought)

Although the change you have done are correct, by putting the name before the domain, if I where t change that in the updater all current files that all developer have made would be invalid.

The cahnge purposed in this PR will enable tracking again.

**Comment by pnbruckner** [comment]
@ludeeus 

Now I'm very confused. Are you saying I should swap the names back to what they were before? Will that work with all versions of custom_updater? And what about when a custom component is first installed. Even though I suggested custom_updater should not use the element name when deciding what directory to create (but rather use the local_location parameter), and even after you made the change, the last time I looked it still _did_ use the element (sometimes - I think when resources was note used.) So if I swap the names back then anyone who tries to install one of these for the first time, it will fail.

**Comment by ludeeus** [comment]
yes, the main keys should be as in this PR it would then be the same structure as [this](https://github.com/custom-components/information/blob/master/repos.json).

I tried to install life360 with this now `{"element":"device_tracker.life360"}` using https://bin.halfdecent.io/raw/akisodakiz and it was placed in  `custom_components/life360/device_tracker.py`

About support for this with earlier versions, frankly, I have no clue...
The current state of the code and documentation is a shit show.... and the past weeks I have only been able to do hotfixes (which have made it even worse, like painting over a rusty car...)

**Comment by pnbruckner** [comment]
@ludeeus 

Yes, I understand that the great migration has caused us all no end of trouble. But reverting the element (or main key) names back to the way they were is just going to cause more confusion in the future, because they won't match how the code is actually laid out.

In fact, now _all_ custom components should probably have an `__init__.py`, even if it's empty. So, e.g., the life360 "device_tracker platform" should probably be turned into a life360 "component", and the json entry should probably be like this:
```
  "life360": {
    "updated_at": "2019-02-22",
    "version": "2.8.0",
    "local_location": "/custom_components/life360/__init__.py",
    "remote_location": "https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components/life360/__init__.py",
    "visit_repo": "https://github.com/pnbruckner/homeassistant-config",
    "changelog": "https://github.com/pnbruckner/homeassistant-config/blob/master/docs/life360.md#release-notes",
    "resources": [
        "https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components/life360/device_tracker.py"
    ]
  },
```
With an empty `life360/__init__.py`, of course, and the `__version__` variable moved to this new file.

I'm hesitant to make any further changes until you get a chance to think this through some more.

**Comment by ludeeus** [comment]
I will most likely not change or add anything major in a long time now.

**Comment by pnbruckner** [comment]
@ludeeus 

I can certainly understand that.

The more I think about what I said above, the more I think I should do this. I.e., change all of my custom "components" to actual components. Can you confirm, if I do this, that it will not cause further problems, and hopefully will resolve the current problems people are having with my json file?

**Comment by ludeeus** [comment]
I personally like the component route, I can not think of a reason why that should not work.

**Comment by GaryOkie** [comment]
Phil - so as a Hassio 88.x user,  if I were to change custom_updater to use the original custom_components_**old**.json (temporarily!) - should expect it to work, even though the files have migrated to the new structure?

**Comment by ludeeus** [comment]
@GaryOkie if you have moved the files locally that will not work.

**Comment by pnbruckner** [comment]
@GaryOkie, no, I don't think so. I will (hopefully soon) update custom_components.json to make all my custom code "components" instead of "platforms." But first I need to create `__init__.py` files for them and move the `__version__` variables to the new `__init__.py` files. I'll also need to update custom_components_old.json so it points to specific commits so people using that don't get screwed. Until I make all these changes, and get a chance to test them, you (and everyone else) will just have to sit tight. It's a mess, but hopefully there's light at the end of the tunnel! 😃

**Comment by GaryOkie** [comment]
Great - thanks Phil.   I understand and will try real hard to sit tight :)

have you considered  a very temporary https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components_hack.json   that has the keys in the "reversed" old format but points to the migrated files in the new domain.xxx format?

**Comment by pnbruckner** [comment]
@GaryOkie that's what custom_components_old.json is right now.

**Comment by pnbruckner** [comment]
@ludeeus, well going the "pure component" route won't work either. E.g., what if someone has or creates a custom composite sensor? Then my `composite/__init__.py` from my custom composite device_tracker would collide with their `composite/__init__.py` from their custom composite sensor. Argh!!

So, should I just put my element names / main keys in my custom_components.json back the way they were? I.e., `composite.device_tracker` goes back to `device_tracker.composite`, etc.? And you're saying that will work, even though the folder the file ends up in is named `custom_components/life360`, not `custom_components/device_tracker`?

**Comment by pnbruckner** [comment]
@GaryOkie, actually, I was wrong. custom_components_old.json is _not_ what you were asking for. For you probably already figured that out.

**Comment by GaryOkie** [comment]
@pnbruckner   yep, I did, thanks for confirming.   Sitting even tighter for now.   PITA for sure.

**Comment by ludeeus** [comment]
Without a centralized place for a developer to publish/register component, there will always be an issue with naming, that is one of the problems I hoped to solve with https://github.com/custom-components, and that it would be easier for users to find, and when a dev gets an idea there would be fewer places to check if someone else already has made it (that has happened to me multiple times).

When I tested it a couple of hours ago I used the content from this PR (and the latest version of custom_updater) the result was this:
image

**Comment by pnbruckner** [comment]
Yes, a centralized location would definitely have its advantages. I might have put my stuff there when I started if I had known it existed.

Yes, I just tried the same thing and it worked fine on my 0.89.x dev checkout. I will probably merge this PR soon.

**Comment by SurfingSpider** [comment]
Thanks for the hard work both of you. Life360 component popped up in my tracker card today. Without any changes on my end.

**Pull request merged**
